### ISSUE TITLE
Clarify our future plans to readers

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDataScience/JuliaDataScience#110]
From some valuable suggestions by Evgeny Pogrebnyak on Twitter (https://twitter.com/PogrebnyakE/status/1435707529137463302). Evgeny argues that a book title "Julia Data Science" should contain more than just plotting and dataframes transformations. We need to clarify to readers that for version 2, we plan to add:

- Statistics (for example, `GLM.jl` and `HypothesisTests.jl`)
- `AlgebraOfGraphics.jl`
- Machine Learning (`MLJ.jl`)
- maybe other things?

**Comment by storopoli** [comment]
Statistics I have a very biased preference (I think @rikhuijzer has the same) towards Bayesian statistics. So I would do something Bayesian in the Statistics.

I am adding Machine Learning with `MLJ.jl`

**Comment by epogrebnyak** [comment]
Few ideas: 

- readers should appreciate you are outlining a whole journey for them, not just the start of the path - this helps avoid negativity "why is this dataframes snd charts and not beyond"
- you do not have to lock into specific packages at the point for statistics, machine learning, neural networks
- especially given Julia has a young ecosystem, where same hings can be done in different packages - nice if you can address that
- even more subtle not always clear you can join functionality from different packages
- think of branding the book as vol1. or as semver, so you attract readers long-term

Couple separate ideas:

- depending how you see at can add info about alternative Julia textbooks, as refrence to the reader
- I was reviewing a Julia book from a publisher, a bit weaker one, and they looked for more authors, you can keep the book open and publish to another channel
- your work makes me rethink and idea of a manual that takes a topic in data science workflow and presents solutions in R, python and julia - will send a link later

**Comment by rikhuijzer** [comment]
We've all three read your suggestions and had discussions about it. Also, the roadmap is added to the homepage of the book. That's why I'll close this issue for now.
