### ISSUE TITLE
Statistics Chapter

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#112]
A final chapter with basic statistics using both `DataFrames.jl` and `Makie.jl`. Each concept we should give the intuition behind it and also get into mathematical details.

We should cover:

- [x] Statistics: Quick Intro and Importance
- [x] Central Tendencies Measures: mean, median and mode
- [x] Dispersion Measures: standard deviation, variance, mean absolute deviation, quartile and IQR
- [x] Dependence Measures: Correlation and Covariance
- [x] Distributions
	- [x] Normal vs Non-Normal
	- [x] Discrete vs Continuous
	- [x] PDF
	- [x] CDF
- [x] Statistical Visualizations
	- [x] Box plots
	- [x] Histograms
	- [x] Density plots
	- [x] Anscombe Quartet

**Comment by AriMKatz** [comment]
Hi,

This is a great book. I'm not sure about license compatibility or if there's room for collaboration, but I wanted to point you to: https://github.com/unbalancedparentheses/data_science_in_julia_for_hackers 

Which takes a bayesian approach to introducing stats. Also has ML, sciml and TS forecasting chapters.

**Comment by storopoli** [comment]
@AriMKatz DS in Julia for Hackers is am amazing resource. I would like to hear @rikhuijzer and @lazarusA  opinions also.
