### ISSUE TITLE
is creating functions to avoid multiple variables really a good choice? 

### ISSUE THREAD

**Issue by hdcpereira** [JuliaDataScience/JuliaDataScience#118]
Hello there! 

In the 4th chapter we find the comment bellow

>NOTE: This works, but there is one thing that we need to change straight away. In this example, we defined the variables name, grade_2020 and df in global scope. This means that these variables can be accessed and edited from anywhere. If we would continue writing the book like this, we would have a few hundred variables at the end of the book even though the data that we put into the variable name should only be accessed via DataFrame! The variables name and grade_2020 where never meant to be kept for long! Now, imagine that we would change the contents of grade_2020 a few times in this book. Given only the book as PDF, it would be near impossible to figure out the contents of the variable by the end. We can solve this very easily by using functions.

Is that really necessary? I think its way more readable to let what is being explained outside a function. I think it would be better for each chapter to have a single Jupyter Notebook. For an example, Ch4_dataframes.ipynb, where every variable would be constrained in this chapter, avoiding the variable to be accessed anywhere.

**Comment by storopoli** [comment]
@hdcpereira we do not use Jupyter Notebooks, we use https://github.com/rikhuijzer/Books.jl.
What we are arguing is that the whole culture of Jupyter Notebooks is not a very good approach to reliable software engineering practices. We describe this in [Section 1.2 - Software Engineering](https://juliadatascience.io/engineering) and we think that every PhD candidate, researcher or industry analyst should treat their analyses as a reproducible and robust package with functions and documentation.

**Comment by hdcpereira** [comment]
Agreed. We are really not used to see quality code being written in jupyter notebooks.
