### ISSUE TITLE
makie.jl: ERROR: LoadError: UndefVarError: Downloads not defined

### ISSUE THREAD

**Issue by bardo84** [JuliaDataScience/JuliaDataScience#145]
Hi,

I get an
```
ERROR: LoadError: UndefVarError: Downloads not defined
Stacktrace:
 [1] top-level scope
   @ o:\Julia\makie.jl:604
in expression starting at o:\Julia\makie.jl:604
```
Commented out.

And on execution for all demo functions:
```
ERROR: UndefVarError: Options not defined
Stacktrace:
 [1] custom_plot()
   @ Main o:\Julia\makie.jl:16
 [2] top-level scope
   @ REPL[12]:1
```
Commented out.

On execution, 
>custom_plot()

no error, no plot appears.

**Comment by storopoli** [comment]
This could be a Julia version error. Since `Downloads` is a standard library module. Could you please post your Julia version and project status with package versions?

**Comment by bardo84** [comment]
Hi,
julia> VERSION
v"1.7.0-rc1"

(@v1.7) pkg> st
      Status `C:\Users\xxx\.julia\environments\v1.7\Project.toml`
  [6e4b80f9] BenchmarkTools v1.2.0
  [13f3f980] CairoMakie v0.6.5
  [e9467ef8] GLMakie v0.4.6
  [4b11ee91] Gaston v1.0.4
  [d0351b0e] InspectDR v0.4.3
  [c3a54625] JET v0.5.0
  [ee78f7c6] Makie v0.15.2
  [961ee093] ModelingToolkit v6.5.2
  [f0f68f2c] PlotlyJS v0.18.7
  [91a5bcdd] Plots v1.22.3
  [c46f51b8] ProfileView v0.6.10
  [295af30f] Revise v3.1.20
  [276b4fcb] WGLMakie v0.4.6

**Comment by storopoli** [comment]
I haven’t played yet with Julia 1.7. @rikhuijzer any suggestions?

**Comment by rikhuijzer** [comment]
> Hi,
> 
> I get an
> 
> ```
> ERROR: LoadError: UndefVarError: Downloads not defined
> Stacktrace:
>  [1] top-level scope
>    @ o:\Julia\makie.jl:604
> in expression starting at o:\Julia\makie.jl:604
> ```
> 
> Commented out.
> 
> And on execution for all demo functions:
> 
> ```
> ERROR: UndefVarError: Options not defined
> Stacktrace:
>  [1] custom_plot()
>    @ Main o:\Julia\makie.jl:16
>  [2] top-level scope
>    @ REPL[12]:1
> ```
> 
> Commented out.
> 
> On execution,
> 
> > custom_plot()
> 
> no error, no plot appears.

Hi, @bardo84. Could you elaborate a bit on what you're trying to achieve?

**Comment by bardo84** [comment]
I was trying to run [this ](https://github.com/JuliaDataScience/JuliaDataScience/blob/main/src/makie.jl)file.

**Comment by rikhuijzer** [comment]
> I was trying to run [this ](https://github.com/JuliaDataScience/JuliaDataScience/blob/main/src/makie.jl)file. Maybe I did not get your question.

Okay. That file is part of the JDS (Julia Data Science) package. It is not intended to be run as a separate script. We explain why in Section [1.2](https://juliadatascience.io/engineering).

Is your intention to re-create the plots and modify them ever so slightly to get the hang of plotting? In that case, it's probably easiest to run [Pluto.jl](https://github.com/fonsp/Pluto.jl) and copy paste the code from this book. Of course, there are easier ways than this to do it, but I don't know what your experience level is with Julia and what development environment you are using. Pluto is the safest bet to get things running, especially when plotting is involved. An demo of Pluto with plotting is at https://www.youtube.com/watch?v=jdEqGOv8ycc.

**Comment by bardo84** [comment]
Package dependency, ok, understand. 
My experience level is low in this regard. 
Is there a way to write the script that it would have requested to load the package?

**Comment by rikhuijzer** [comment]
> My experience level is low in this regard.
> Is there a way to write the script that it would have requested to load the package?

Then definitely checkout Pluto.jl. It can manage package dependencies for you automatically. Also, most (if not all) of our Makie.jl plots are stand alone, meaning that you can just copy paste the code in Pluto and see the results. Just copy paste

```
using Makie
using CairoMakie
scatterlines(1:10, 1:10)
```

and it should work. See the aforementioned YouTube video for instructions on how to get Pluto.jl running.

**Comment by bardo84** [comment]
OK, thx for your help!

**Comment by storopoli** [comment]
Oh sorry. I though you were trying to run the source code for the book. Rik’s suggestions are great. Don’t hesitate to reach out the Julia’s discourse (discourse.julialang.org).
