### ISSUE TITLE
Launch the Printed Book at Amazon.com

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#17]
We need to:

- [x] Normalize functions and syntax to blue codestyle, also accordingly to DataFrames, Plots, Makie, AoG docs
- [x] Create a PDF with syntax highlighting (#15)
- [x] Create an Author Profile at Amazon.com (both @storopoli, @rikhuijzer  and @lazarusA )
- [x] Get a ISBN (Amazon Provides a [free one](https://kdp.amazon.com/en_US/help/topic/G201834170))
- [x] Adapt the book to Amazon.com format
- [x] Create cover (#148) 
- [x] Write a summary
- [x] Tag a "first edition" release on this repository

**Comment by rikhuijzer** [comment]
Just discussed with Lazaro. Size is gonna be 6.14" x 9.21" (15.6 x 23.39 cm). Available sizes: https://kdp.amazon.com/en_US/help/topic/G201834180.

**Comment by rikhuijzer** [comment]
For 230 pages, the cover will look as follows (https://kdp.amazon.com/en_US/cover-templates):

![image](https://user-images.githubusercontent.com/20724914/134786525-d8835fe2-09bf-444b-8897-bf850649cae4.png)

I plan to make an automated build soon for the cover via either Makie or LaTeX.

**Comment by rikhuijzer** [comment]
Which paper?

![image](https://user-images.githubusercontent.com/20724914/135903049-7f94b50c-54ce-45ab-88c3-4718e5f4a686.png)

versus

![image](https://user-images.githubusercontent.com/20724914/135903126-9bd6c148-ddfe-4115-8e47-b3d73642a902.png)

I'd say the cheaper one to make the book more easily available.

**Comment by rikhuijzer** [comment]
Book margins are approved now after https://github.com/rikhuijzer/Books.jl/commit/ce1e8013f7e3928b1ce32ab8dac77f46e84da961:

![image](https://user-images.githubusercontent.com/20724914/135915045-4e64091d-6b44-43a9-b55e-9f60ea6b50d6.png)

**Comment by storopoli** [comment]
What about the price difference from the standard vs premium?
