### ISSUE TITLE
Text outside margins in PDF

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDataScience/JuliaDataScience#170]
On page 165:

![image](https://user-images.githubusercontent.com/20724914/136915408-6edc1355-2fd5-4012-83e2-244b32b0286b.png)

On page 184:

![image](https://user-images.githubusercontent.com/20724914/136915536-b433c337-1413-4115-ab5e-e6a7f6f2dd78.png)

This probably requires a fix in the PDF template.

**Comment by storopoli** [comment]
> LaTeX messes up because there is too much stuff that has to be aligned

is what I would bet that is happening.

We could do something like:

```julia
combine(groupby(df, :dataset),
                [:x, :y] .=> round_up .∘ [mean std] .=>  [:x_mean, :y_mean. :x_std, :y_std],
                [:x, :y]  => round_up ∘ cor => :x_y_cor)
```

What you think?
