### ISSUE TITLE
Announcements and Publicity

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#19]
- [ ] Official Julia here: https://julialang.org/learning/books/
- [ ] Extra-Official here: https://github.com/svaksha/Julia.jl/blob/master/Resources.md#books
- [x] Make an announcement at Discord `[ANN] Books.jl and JuliaDataScience`
- [ ] HackerNews

**Comment by rikhuijzer** [comment]
For the Discord, I‘m thinking about doing an `[ANN] Books.jl and JuliaDataScience` announcement. I think that they would complement each other very well in the announcement
