### ISSUE TITLE
Logo for Julia Data Science Organization 

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#2]
We need a logo I will talk to someone who can do that for me at UNINOVE. Any thoughts @rikhuijzer ? We should move anything stats/Bayesian so to not confuse with future endeavors.

Maybe something with Tabular Data or Line Plots. We should definitely use Julia colors.

- [x] Update JuliaDataScience GitHub Organization Logo
- [x] Update JuliaDataScience Book favicon site icon

**Comment by rikhuijzer** [comment]
> We need a logo I will talk to someone who can do that for me at UNINOVE.

:+1: 

> Maybe something with Tabular Data or Line Plots. We should definitely use Julia colors.

Generating a beautiful plot via one of the libraries sounds like a plan.

**Comment by storopoli** [comment]
Yeah I agree. But it must be recognizable and distinguishable while also communicating the idea of Julia Data Science Organization/Book

**Comment by rikhuijzer** [comment]
Good point

**Comment by rikhuijzer** [comment]
It would be really cool if we could generate a logo from code. That way, we can also generate the favicon easily.

For example, maybe something like

![image](https://user-images.githubusercontent.com/20724914/122583687-d3dbdb80-d059-11eb-94bc-88c3791a2d0d.png)

or

![image](https://user-images.githubusercontent.com/20724914/122583825-f2da6d80-d059-11eb-9eea-f52b3c5609c5.png)

Source https://discourse.julialang.org/t/seven-lines-of-julia-examples-sought

**Comment by storopoli** [comment]
Current suggestions
![Julia_Data_Science_Logo2](https://user-images.githubusercontent.com/43353831/123151405-cc417b80-d439-11eb-8d18-c5e4dc4f90f9.png)
![Julia_Data_Science_Logo3](https://user-images.githubusercontent.com/43353831/123151408-ccda1200-d439-11eb-8bd7-ac4b37804941.png)
![Julia_Data_Science_Logo4](https://user-images.githubusercontent.com/43353831/123151411-cd72a880-d439-11eb-9ec2-a7ec2b994bd9.png)
![Julia_Data_Science_Logo5](https://user-images.githubusercontent.com/43353831/123151412-cd72a880-d439-11eb-9a36-397fdc6b8754.png)
![Julia_Data_Science_Logo](https://user-images.githubusercontent.com/43353831/123151393-c9df2180-d439-11eb-8524-d59f37fd3892.png)

**Comment by storopoli** [comment]
I think we have a winner:

![Julia_Data_Science_Logo](https://user-images.githubusercontent.com/43353831/123455749-75ae7b80-d5b8-11eb-84a4-82f1786ad319.png)
