### ISSUE TITLE
Different repo for version 2?

### ISSUE THREAD

**Issue by lazarusA** [JuliaDataScience/JuliaDataScience#202]
Guys,
probably is too early, but I have some material using Flux that I would like to start putting up. Not revision necessary yet, just starting material (more like notes), but it will be definitely breaking changes. Could we have a different repo within the organisation for that?

**Comment by storopoli** [comment]
Nice, Flux is one of my favorites packages.

I don't know about a different repo. Is it necessary? If yes, I am all up for it.

**Comment by rikhuijzer** [comment]
> Could we have a different repo within the organisation for that?

Easiest would be to work in this repo, try to keep breaking changes to a minimum and combine that with one or more notes that things are work in progress.

**Comment by lazarusA** [comment]
But maybe we don't need it here. @rikhuijzer did already one archive for version 1. As long as we keep an archive along the way I think is ok to keep working in the main repo.
