### ISSUE TITLE
Add an amazon review banner

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDataScience/JuliaDataScience#219]
Hey folks, you all should add a big banner on the book page asking folks to leave a review on Amazon. This will help increase the visibility of the book significantly!

**Comment by storopoli** [comment]
We could add a footer?

**Comment by logankilpatrick** [comment]
That would be good. And the idea is that you don’t technically need to buy the book on Amazon to write a review. If you use the free version, you can still write a review on Amazon. 

Best, 
Logan Kilpatrick
