### ISSUE TITLE
improve typographical stuff

### ISSUE THREAD

**Issue by Mo-Gul** [JuliaDataScience/JuliaDataScience#221]
As I already stated in e.g. https://github.com/JuliaDataScience/JuliaDataScience/pull/215/commits/e8e1d11ed6386f8bcd552abbfd9ab058c3176b51 it would nice to make some sections unnumbered when there is no second section on that level.

When I have seen this correct, this *should* be possible by appending the section entry by ` {-}` as e.g. can be seen in

https://github.com/JuliaDataScience/JuliaDataScience/blob/56151f0f6d69ad4c62945aa1deb3169af90ef9ad/contents/index.md#L1

So if you consider it would be nice to have that I'll redo the suggestions in a new PR. Especially if it is that easily doable.

---

PS:  
I am not sure if my newest comments in #217 have been noticed by one of you, since I have added them *after* the PR was merged. Thank you for your comments!

**Comment by rikhuijzer** [comment]
> As I already stated in e.g. e8e1d11 it would nice to make some sections unnumbered when there is no second section on that level.

Could you elaborate a bit more on this? What would be a section where you would suggest to avoid numbering?

**Comment by Mo-Gul** [comment]
Sure. In the mentioned commit you find the first two additions starting with `<!-- NOTE:`. The sections one line above them I would make unnumbered. Speaking in section numbers shown on <https://juliadatascience.io> these would be

- 1.0.1
- 1.1.1
- 3.3.1.1

up to and including chapter 3. (The rest I didn't read so far.) The reason is that there are no corresponding x.2 sections (as is also written in the comments).

**Comment by rikhuijzer** [comment]
I do agree that you're suggestion is probably better :slightly_smiling_face: For me it would not be a priority to fix since I would rather spend time on new content, but I would be open to PRs for this issue :smile:

**Comment by Mo-Gul** [comment]
@rikhuijzer, sure, having new stuff is always a great idea and that is why I happily provide pull requests (when I am able to accomplish the task in question myself). That way I can give something back.

If I would be asked to "missing" things, I would love to read something about

- units  
  (I guess that would be [`Unitful.jl`](https://github.com/PainterQubits/Unitful.jl))
- uncertainties  
  (I guess this will be either [`Measurements.jl`](https://github.com/JuliaPhysics/Measurements.jl) or [`NeXLUncertainties.jl`](https://github.com/usnistgov/NeXLUncertainties.jl))

Finally, it would be great if you (or another author) could comment on the "PS" of my first post in this issue. That is, on my newest comments to the unresolved stuff in PR #217.

**Comment by rikhuijzer** [comment]
Yes thank you for your work :slightly_smiling_face: 

Also thank you for the feedback :+1:
