### ISSUE TITLE
[dataframes_select] not the same selection

### ISSUE THREAD

**Issue by Mo-Gul** [JuliaDataScience/JuliaDataScience#228]
The lines

https://github.com/JuliaDataScience/JuliaDataScience/blob/b5582d29a9afa300e0a124ad2820389c386c04cc/contents/dataframes_select.md#L48-L56

don't give the same result as the previous example ... (where `:id` is *not* shown)

I think you need to rephrase the text.

**Comment by rikhuijzer** [comment]
Which text is exactly incorrect here? :slightly_smiling_face: I've tried to find it but couldn't unfortunately

Thank you for your very critical read through, by the way :heart:

**Comment by Mo-Gul** [comment]
Line 49 is wrong. It is stated that we achieve "the same". By that I assume that now follows some code that gives the same result as the previous example (the lines above line 48). But line 54 yields a table that has column `:id` included while the previous doesn't.

Regarding the "critical read through": With great pleasure!! "Proofreading" is much much simpler than **writing** the book! And when I try to *learn* Julia and I think "that should be different than is stated here" I here have the opportunity to ask the authors directly. And luckily you also welcome these questions and "answer" them 🤩🥇

**Comment by rikhuijzer** [comment]
> Line 49 is wrong. It is stated that we achieve "the same". By that I assume that now follows some code that gives the same result as the previous example (the lines above line 48). But line 54 yields a table that has column :id included while the previous doesn't.

Awesome. That was a very tough one to spot. Should be fixed now in 9026788 and online in about half an hour.

> And luckily you also welcome these questions and "answer" them :star_struck: :1st_place_medal:

That's a very nice way to look at it! Thank you!

**Comment by Mo-Gul** [comment]
Although it is now "formally" correct, I think it is a bad example now to show a mix for selecting and not selection columns. I don't think that anybody would come to the idea to write "use column A and don't use column A" (at least me as a beginner of Julia would never have come to that idea. But maybe this is because I don't have/didn't have a good enough understanding so far)

https://github.com/JuliaDataScience/JuliaDataScience/blob/9026788181c9e3368fa39ae25e1ae9d488bd53c5/contents/dataframes_select.md#L44

I suggest to do the following:  
Change e.g.

https://github.com/JuliaDataScience/JuliaDataScience/blob/9026788181c9e3368fa39ae25e1ae9d488bd53c5/contents/dataframes_select.md#L23

to

```jl
select(responses(), "id", "q2", "q1")
```

and already note there that the order of the *returned* columns correspond to the order of the *input* columns. Then you could say, that adding `:` adds all the columns that weren't called already with e.g.

```jl
select(responses(), "id", "q2", "q1", :)
```

Said that the two `Not` examples can be shown which are straight forward. After that you can show the old mixed example again which should also be quite intuitive then. And as a final example you can show a mixture of stating *selected columns*, followed by *excluded columns* followed by "remaining columns", e.g.

```jl
select(responses(), 1, :q5, Not(:q3), :)
```

That is the ultimate test to see if one has understood what is happening. Because I thought that this would result showing columns 1,5,2,4, i.e. I thought `:` only returns the 4 because the 3 was excluded. But now I know that
- stating columns explicitly (like `1` or `:q5` state exactly only these columns,
- `Not(...)` states *all* columns except the ones that were already selected/stated and the ones listed as argument to `Not`,
- and `:` states all (still) remaining columns.

(Maybe one could emphasize this by stating (and showing an example) that each column can only be selected *ones*, i.e. trying

```jl
select(responses(), 1, :q5, :q5)
```

yields an error.)

Hopefully my suggestion is not too weird and you know what I want to say. If not, feel free to ask for clarification and/or provide a (draft) PR which I am happy to review.

**Comment by Mo-Gul** [comment]
Sleeping a night over it, maybe it would even be better to have the following order of features. I will refrain from explanations at this point to have a rather short comment. As before, I'll be happy to explain or discuss anything if needed/wanted. (With "select" in the examples I mean e.g. `:q3`.)

1. simple select example
2. multiple select example with not straight-forward order (see previous comment)
3. columns can only be selected *once* example
4. select all columns using `:` which is known from section ...
5. combine (1. or 2.) with 3. --> `:` is clever and removes already selected columns
6. (simple `Not` example)
7. `Not` example excluding multiple columns
8. combine select and `Not` --> `Not` is also clever to remove already selected columns
9. (combine select, `Not` and `:` as ultimate example)

**Comment by rikhuijzer** [comment]
I'm currently in the middle of some other things ([Skan.jl](https://github.com/rikhuijzer/Skan.jl) and a paper). I've wrote it on my task list and will take a proper look at a later moment :+1:

**Comment by Mo-Gul** [comment]
No hurry. It is just a suggestion, and since we all spent our spare time on "these" (kinds of) projects, we will invest the time, when we have it :snail:
