### ISSUE TITLE
Notation discussion points

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDataScience/JuliaDataScience#23]
Notation discussion points from #20:

1. Always using : before the start of a code block.
1. Mentioning functions like `DataFrame` as `DataFrame()` or `DataFrame(...)`.
1. My suggestion: only Julia objects between backticks and filenames and extension names between quotation marks (like Julia's strings).

**Comment by storopoli** [comment]
1. agreed!
2. I prefer `DataFrame()` without the `...` which would imply something being splatted which in turn can generate confusion and ambiguity
3. I did not understood this, could you give an example?

**Comment by rikhuijzer** [comment]
2. Okay, fair that `...` is not a good solution. Yet, I think that `DataFrame()` or `CSV.write()` causes similar confusion. In code, it would mean calling the function without arguments. For example,
```
julia> using CSV

julia> CSV.write()
ERROR: MethodError: no method matching write()
Closest candidates are:
  write(::Tables.Schema{names, types} where types, ::Any, ::Any, ::Any; append, header, bufsize) where names at /home/rik/.julia/packages/CSV/Zl2ww/src/write.jl:195
  write(::Nothing, ::Any, ::Any, ::Any; append, header, bufsize) at /home/rik/.julia/packages/CSV/Zl2ww/src/write.jl:223
  write(::Any; kwargs...) at /home/rik/.julia/packages/CSV/Zl2ww/src/write.jl:134
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[10]:1
```
which can be very confusing to beginners, I think. In the Julia documentation, references to methods are just via backticks, so it would be `DataFrame` or `CSV.write`. For instance, 

"If you want to check that each converted value is a valid code point, use the `isvalid` function:" ([source](https://docs.julialang.org/en/v1/manual/strings/)) and

" It also provides a single general outer `Point` constructor that takes pairs of real arguments" ([source](https://docs.julialang.org/en/v1/manual/constructors/)).

3. You suggested in the PR to change something about the CSV extension and filename from "myfile.csv" to `myfile.csv`. I would prefer the former, due to it being more consistent with the Julia code since "myfile.csv" is a String and not some Julia object like a struct, function or method. We could also do a combination of your and my suggestion, namely `"myfile.csv"`.

**Comment by storopoli** [comment]
2. Let's follow Julia syntax. So all functions would be referenced as `function` then
3. Let's follow also Julia syntax. So "myfile" instead of the `"myfile`"

I will make the following changes in Why Julia and Julia 101 sections

**Comment by rikhuijzer** [comment]
This afternoon, I've updated Books.jl to incorporate some more features around `@sco`. I'm now trying to apply those features wherever they are suitable.

This made me run into the following. We say that we adhere to the Blue codestyle. However, we don't do this for triple-quotes currently. For example,
```
sco(
"""
typeof(1.0:10.0)
"""
)
```

From the style guide:

> Triple-quotes and triple-backticks written over multiple lines should be indented.  [...]
```
# Yes:
str = """
    hello
    world!
    """
cmd = ```
    program
        --flag value
        parameter
    ```

# No:
str = """
hello
world!
"""
cmd = ```
      program
          --flag value
          parameter
      ```
```

So, how about adhering to:

```
s = """
    typeof(1.0:10.0)
    """
sco(s)
```

Or, for short code, just:

```
sco("typeof(1.0:10.0)")
```
or
```
s = "typeof(1.0:10.0)"
sco(s)
```
which looks a bit weird, but might be the most reasonable because you do more or less one thing per line. With this last one, we can easily add the keyword arguments:

```
s = "typeof(1.0:10.0)"
sco(s; process=string)
```

and this last one is most consistent with the multiline version:

```
s = """
    typeof(1.0:10.0)
    """
sco(s; process=string)
```

**Comment by storopoli** [comment]
Yeah it is gonna be a pain to change all this. Do you think you can do a regex replace trick?

**Comment by rikhuijzer** [comment]
It’s okay, I think.

What is your opinion on the styles? Any preference? 🙂 Or, do you have arguments to stick to the current way?

**Comment by storopoli** [comment]
I mean we could leave it as it is and just follow blue codestyle in the HTML/PDF-visible code?

**Comment by rikhuijzer** [comment]
@storopoli what do you think about column names? I know that David in MCMCChains prefered to use "column x", but I think that `:x` could be more clear. Hard to say though. What are your thoughts?

**Comment by storopoli** [comment]
I also agree with `:x`
