### ISSUE TITLE
Text inconsistent with code

### ISSUE THREAD

**Issue by guixinliu** [JuliaDataScience/JuliaDataScience#232]
Hi. @rikhuijzer .

I found text there can not match up with the following code. 

https://github.com/JuliaDataScience/JuliaDataScience/blob/b5582d29a9afa300e0a124ad2820389c386c04cc/contents/dataframes_transform.md#L91-L99

More specifically, you said **all of their grades** in the text , but you used **boolean OR  operator `||`** in the code.
My suggestion is the least change, namely `all` -> `any`.

**Comment by rikhuijzer** [comment]
It makes the most sense that someone who passes had above 5.5 on either one of the grades. Probably I meant to type that in the text, but typed all. It's fixed now.

Thanks for reporting this!
