### ISSUE TITLE
Getting Data

### ISSUE THREAD

**Issue by rbl100** [JuliaDataScience/JuliaDataScience#233]
I have to collect data from log files and other sources before I can process it.  Maybe some examples of file IO, regex and text processing would be helpful additions.

**Comment by rikhuijzer** [comment]
Ah yes sounds very good 👍 Some patterns are indeed very useful but hard to figure out, e.g. to remove all lines starting with "hide"

```
lines = split(str, '\n')
filter!(!startswith("hide"), lines)
return join(lines, '\n')
```

Could you give some steps that you do when logging? If I know the tasks then maybe adding a section could be straightforward

Thanks for the feedback by the way!

**Comment by rbl100** [comment]
An explanation of what I need to do is comb thru 100-200 log files looking for results or failure messages.  Unfortunately the programs that write the messages don’t use a uniform format so each category of message looks a little different. Most do have time stamps.   Some have numerical results, others are textual.  Sometimes I have to find a line then look back one or two lines.

My goal is to build a data frame that I can then analyze and build reports from.

I will use the hints you give below.  Thanks.

**Comment by storopoli** [comment]
Closing this, feel free to reopen if necessary.
