### ISSUE TITLE
Why Julia,  `@code_llvm` output mistake

### ISSUE THREAD

**Issue by alexbakus** [JuliaDataScience/JuliaDataScience#253]
In Why Julia, the line explaining LLVM code translation, should read `@code_llvm outer(3)` instead if `@code_llvm inner(3)`

The output for `@code_llvm inner(3)`  is:

```
define i64 @julia_inner_7818(i64 signext %0) #0 {
top:
    %1 = add i64 %0, 3
    ret i64 %1
}
```

There is also a slight error with the output as copied, because it reads `@julia_my_function_3810` in the llvm output and not the inner or outer evaluation. 

https://github.com/JuliaDataScience/JuliaDataScience/blob/8e12ccfd75357474ec55c1f445e873914d62bb36/contents/why_julia.md

**Comment by rikhuijzer** [comment]
There was another mistake still, `@code_llvm` showed the stuff for `inner` instead of `outer` while `outer` is more interesting to show. In 7be6ea5 I fixed this. In 30 minutes, it should show the following:

```julia
julia> inner(x) = x + 3
inner (generic function with 1 method)

julia> outer(x) = inner(2 * x)
outer (generic function with 1 method)

julia> outer(3)
9
```

```
julia> @code_llvm debuginfo=:none outer(3)
define i64 @julia_outer_232(i64 signext %0) #0 {
top:
  %1 = shl i64 %0, 1
  %2 = add i64 %1, 3
  ret i64 %2
}
```
