### ISSUE TITLE
Outdated informaiton on Makie

### ISSUE THREAD

**Issue by Moelf** [JuliaDataScience/JuliaDataScience#256]
>By default, Makie.jl is reexported by every backend, so you only need to install and load the backend that you want to use.

is no longer true, see for example GLMakie.jl is deprecated

**Comment by storopoli** [comment]
Thanks, we would love a PR with better clarifications. 😄

**Comment by Moelf** [comment]
After giving it more read I think it's fine, Makie moved to monorepo. I guess we don't need the active!() But it doesn't hurt, closing the issue as there's no actionable item


Great book!!
