### ISSUE TITLE
Content of the book: static or dynamic?

### ISSUE THREAD

**Issue by mgiugliano** [JuliaDataScience/JuliaDataScience#262]
Thank you for adhering and championing the idea of open science and open access.

Is the TOC and themes covered in the book complete and finalised, or meant as a "work in progress" ?
I am looking around for sources in preparing a graduate course in data analysis and notice lack of many topics that might be relevant for STEM.

Thank you for your patience with my question.

**Comment by storopoli** [comment]
Thanks @mgiugliano, the basics of data wrangling and plotting in Julia. It is not STEM-focused. It is a gateway for novices to Julia, specific on how to analyze and plot data.

You can build for any other STEM topic from there.
@lazarusA is planning a neural networks chapter, I am planning a probability/Bayesian modeling chapter (but I have not yet done anything related to that).
