### ISSUE TITLE
PDF has johndoe in the footer

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#27]
![image](https://user-images.githubusercontent.com/43353831/125160940-dd86c980-e155-11eb-9b16-adae80281736.png)

**Comment by rikhuijzer** [comment]
This is not a bug. It's a documented configuration setting: <https://rikhuijzer.github.io/Books.jl/metadata.html>

Fixed in bf28f1bee2c6e9554783510c4408f4146ce9fef4.
