### ISSUE TITLE
2 suggestions for enhancement

### ISSUE THREAD

**Issue by mocalvao** [JuliaDataScience/JuliaDataScience#301]
Hi there,

First of all, congratulations for your book! It is very didactic and I hope it gets the audience it sure deserves. 

I am not certain the creation of a new Issue here is the best way to propose the following suggestions; anyhow, there they go:

(1) create an index

(2) in subsection 3.2.7 ("While Loop"), I noticed that, in the REPL (under Julia version 1.8.3), the use of the global declaration for the variable $n$, is not necessary (though it does not hurt at all). However, this triggered my curiosity and I looked up the official documentation for the [scope of variables](https://docs.julialang.org/en/v1/manual/variables-and-scoping/) and found out, in practice, via the call of the same chunk of code from within a .jl file, that, then it was mandatory. Thus, I suggest, perhaps, concretely, that you at least refer, in a marginal note, for instance, to the relevant link for the official manual. Finally, as per this documentation itself ("Notably missing from this table are [begin blocks](https://docs.julialang.org/en/v1/manual/control-flow/#man-compound-expressions) and [if blocks](https://docs.julialang.org/en/v1/manual/control-flow/#man-conditional-evaluation) which do not introduce new scopes."), it seems to me that the sentence:

"Variables defined inside conditional statements, loops, and functions exist only inside them"

should be corrected to:

"Variables defined inside loops, and functions exist only inside them". 

Regards and cheers once again!

**Comment by storopoli** [comment]
Index is something we might need to do in the `Books.jl` package since it delegates rendering and multiple filetypes outputs to pandoc and pandoc-crossref.

About the use of global variables, we know that this is not ideal, but for the sake of out target audience (newcomers) we still found that it was a good compromise.
Do you have a better example for `while` loop to suggest?

**Comment by mocalvao** [comment]
Hi Jose,
I do not have a better suggestion to illustrate the use of the `while` loop :-). What about deleting the reference to the local scope for variables in an `if block`; this seems to really need amending, does it not?

**Comment by storopoli** [comment]
Too much cognitive load to showcase the `while` loop for beginners.
Do we want them to learn effectively a `while` loop or do we want them to have the best performant `while` loop?

**Comment by HimoriK** [comment]
> Too much cognitive load to showcase the `while` loop for beginners. Do we want them to learn effectively a `while` loop or do we want them to have the best performant `while` loop?

You underestimate the beginner, simply pass the local variable and let them feel confident their loop works.
If you want to explain further add a citation in italics or as a note.

**Comment by storopoli** [comment]
Feel free to reopen if necessary
