### ISSUE TITLE
Replace Disney Copyright Meme in Why Julia

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#33]
We need a new meme for "Data, Data Everywhere"

**Comment by storopoli** [comment]
Guys, what you think?

---
The big question is, do **MEMEs violate copyright?**

Well, the rights of the copyright owner are not **exhaustive** or **absolute**.

So, what happens if YOUR work is made into a meme?
Or, you end up posting a meme on your business page?

Courts usually to measure fair use by the following four areas (often referred to as prongs) outlined in §107 of the Copyright Act:

1. the purpose and character of the use, including whether such use is of a commercial nature or is for nonprofit educational purposes;
2. the nature of the copyrighted work;
3. the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and
4. the effect of the use upon the potential market for or value of the copyrighted work.

It’s been widely held that the first prong of fair use will be satisfied if an artist or any person uses the image for purposes of commentary, criticism, reporting, or **teaching**. In addition, the Supreme Court has unequivocally held that a parody and or a satire may qualify as a fair use image under the Copyright Act since it’s a commentary on an original work.

Source: [The Law Tog](https://thelawtog.com/memes-violate-copyright-law/)
---

Take a look at teaching over there. I don't think we are in danger here.

**Comment by lazarusA** [comment]
In my experience 
 **teaching** just refers to lectures/classrooms and the **nonprofit** part is also not good. After also, doing some [additional  reading](https://www.oif.ala.org/oif/?p=16873) I think that at best our case will be in a grey area.  Plus, no major publisher that I know of has taking the risk of publishing copyright content without the proper consent from the owner. Which, from my reading this should include both, the original source plus the one doing the meme [these things are crazy]. 

Just as an anecdote, when I was teaching back in Mexico, a professor used copyright material without the consent from the owner, and the university was force to pay 1 million pesos (~ 50,000 euros). After that, we were only allow to show images (including memes) without copyrights.

**Comment by storopoli** [comment]
We could remove the image. I don't think we will lose much of the meaning/content.
What you think?

**Comment by lazarusA** [comment]
The image is funny and it conveys a clear message. But I agree that we should remove it. Better to be prevent now than to solve problems later.
