### ISSUE TITLE
Cairomakie cheat sheet has huge file size and appears empty

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaDataScience/JuliaDataScience#345]
@lazarusA do you maybe know why https://juliadatascience.io/makie_cheat_sheets shows no image for the CairoMakie one? Also the front cover is empty. In the PDF, the image does work:

![image](https://github.com/user-attachments/assets/98db8943-0061-48d1-bb9c-3da797ad98be)

Could it be that one is in PNG format and the web in SVG?

**Comment by lazarusA** [comment]
I will take a look.
