### ISSUE TITLE
Chapter 7 Link broken to Makie Docs

### ISSUE THREAD

**Issue by storopoli** [JuliaDataScience/JuliaDataScience#82]
There is a link broken in Chapter 7 `datavisMakie.md`:

In the "See Makie’s documentation for more." It redirects to http://makie.juliaplots.org/stable/backends_and_output.html#Backends-and-Output which is broken.

cc @lazarusA

**Comment by storopoli** [comment]
That was a temporary fix. We need to have this thing sorted out for a static link instead of a hard coded specific version.

**Comment by rikhuijzer** [comment]
Okay. Why do you think the current solution is wrong?

**Comment by storopoli** [comment]
Because in a couple of months from now Makie will be in 0.16, 0.17 or even 1.0. And the reader will click that and will land on a specific documentation version

**Comment by rikhuijzer** [comment]
Do you have a suggestion on how we can improve it? Dev might result in a broken page which is also not ideal I'd say

**Comment by rikhuijzer** [comment]
Ah. I now see that there is a discussion with a solution in the PR.

**Comment by storopoli** [comment]
Yes, sorry I thought you have read that first...

**Comment by lazarusA** [comment]
Ok, this will be solved if this issue gets fixed.  https://github.com/tlienart/Franklin.jl/issues/875 . Otherwise, we will need to come up with a different solution.

**Comment by storopoli** [comment]
@lazarusA I think that tlienart/Franklin.jl#875 has already fixed and we can expect it to propagate to Makie docs in a couple of days

**Comment by storopoli** [comment]
I think we can close this
