### ISSUE TITLE
Section on AlgebraOfGraphics.jl?

### ISSUE THREAD

**Issue by AriMKatz** [JuliaDataScience/JuliaDataScience#95]
Any plans for something on https://github.com/JuliaPlots/AlgebraOfGraphics.jl ?

**Comment by rikhuijzer** [comment]
For the first version of the book, which we are trying to finish now, we decided to remove it (see also #80). In the future, I definitely do hope that we can add it. It depends a bit on how the package evolves and how stable it becomes.
